version: "3.9"
services:
  server:
    build:
      context: ./tech-int3-server
    ports:
      - "3001:3001"

  client:
    build:
      context: . # корень фронта
      dockerfile: Dockerfile
      args:
        # Прокидываем базу API на этапе сборки Vite (внутри docker-сети)
        VITE_API_BASE: "http://localhost:3001/api/v1"
    environment:
      VITE_API_BASE: "http://localhost:3001/api/v1"
    ports:
      - "5173:80" # отдаем nginx наружу на порт 5173
    depends_on:
      - server
